<?php /** @var \VladFilimon\M2BitcoinPayment\Block\Adminhtml\System\Config\Test $block */ ?>
<script type="text/javascript">
require(['prototype'], function(){
//<![CDATA[
    function <?= /* @noEscape */ $block->getJsFunction() ?>() {
        var validationMessage = $('<?= /* @noEscape */ $block->getHtmlResultId() ?>'),
            prefix = 'payment_us_vladfilimon_m2bitcoinpayment_',
            params = {
            'host': $(prefix + 'host').value,
            'port': $(prefix + 'port').value,
            'user': $(prefix + 'user').value,
            'pass': $(prefix + 'pass').value,
            'ssl' : $(prefix + 'ssl').value
        };
        new Ajax.Request('<?= /* @noEscape */ $block->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                var result = '<?= /* @noEscape */ __('Error during connection test.') ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message || result;
                    }
                    if (response.valid == 1) {
                        validationMessage
                            .removeClassName('error')
                            .removeClassName('hidden')
                            .addClassName('success');
                    } else {
                        validationMessage
                            .removeClassName('success')
                            .removeClassName('hidden')
                            .addClassName('error');
                    }
                } catch (e) {
                    validationMessage
                        .removeClassName('success')
                        .removeClassName('hidden')
                        .addClassName('error')
                }
                validationMessage.update(result);
            }
        });
    }
    window.<?= /* @noEscape */ $block->getJsFunction() ?> = <?= /* @noEscape */ $block->getJsFunction() ?>;
//]]>
});
</script>
<div class="actions actions-vfilimon_m2bitcoinpayment-test">
    <button type="button" id="<?= $block->getHtmlId() ?>"
            onclick="javascript:<?= /* @noEscape */ $block->getJsFunction() ?>(); return false;">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
    <div id="<?= $block->getHtmlResultId() ?>" class="message-test hidden"></div>
</div>

